# About this course {.unnumbered}

The course continues building programming fundamentals in Python programming and data analysis. You will learn how to make use of complex data structures, iterate repeated tasks that scales naturally, and create your own functions. You will apply these skills to develop a custom data analysis.

## Target Audience

The course is intended for researchers who want to continue learning the fundamentals of Python programming and how to write custom data analysis functions when dealing with messy datasets. The audience should know how to work with Lists and Pandas Dataframes and conduct basic data analysis, and/or have taken our [Intro to Python](https://hutchdatascience.org/Intro_to_Python/) course.

## Learning Objectives

-   **Understand and distinguish** the use case of data structures to store different types of data.

-   **Implement** code to Iterate over a collection (such as files, elements of a column, or a list of objects) to batch process each item.

-   **Implement** code that has a branching structure depending on input data's condition.

-   **Create** simple, modular functions that can be reused.

-   **Describe** the difference between copying an object vs. referencing an object and how that could affect variables in a data analysis.

## Offerings

This course is taught on a regular basis at [Fred Hutch Cancer Center](https://www.fredhutch.org/) through the [Data Science Lab](https://hutchdatascience.org/). Announcements of course offering can be found [here](https://hutchdatascience.org/training/).
